config/routes.rb
Directories::Engine.routes.draw do
  resources :directories, path: "dir/:dir_type" do
    get :inplace_popup, on: :collection
  end

  root to: 'directories#index'
end

app/controllers/directories/application_controller.rb
module Directories
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/directories/directories_controller.rb
module Directories
  class DirectoriesController < ::DirectoriesController
    respond_to :json, :js
  end
end

app/controllers/directories_controller.rb
# Обеспечивает базовые механизмы CRUD-операций с моделями Directory (концерн)
# Представления контроллера включают в себя функции интеграции Datatables
class DirectoriesController < ApplicationController
  before_action :authenticate_user!
  include DirectoryOverrides

  before_action :validate_user

  @@_directory_controls = {}
  @@_directory_buttons = {}

  helper_method :_directory_attrs
  helper_method :control_for


  helper_method :get_directory_buttons

  before_filter :init_directory
  before_filter :load_type
  before_filter :load_resource, only: [:show, :edit, :update, :destroy]
  before_filter :on_single_resource, only:[:show, :update]

  before_action :set_title

  def index
    per = (params[:length] || 20).to_i
    page = params[:start].to_i / per + 1 if params[:start].present?

    @resources = begin
        @resource_class.elasticsearch(params).result.per(per).page(page).only(:id).load(@resource_class.name.underscore => { scope: -> { @resource_class } } )
    rescue Exception => e
      # byebug
      Rails.logger.debug("="*80)
      Rails.logger.debug(e)
      Rails.logger.debug("="*80)
      resource_collection
    end

    #byebug
    #sleep(0)
    respond_to do |format|
      format.js {}
      format.html { @resources = resource_collection}
      format.json do
        unless params.has_key?(:datatables)
          render "index_for_selectivity"
        end

      end
    end
  end

  def new
    @resource = resource_collection.new
    respond_to do |format|
      format.js {}
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @resource }
      format.js {}
      format.html {}
      format.pdf do
        render pdf: @resource.class.name.underscore, layout: "pdf"   # Excluding ".pdf" extension.
      end

    end
  end

  def edit
    respond_to do |format|
      format.js {}
    end
  end

  def create
    #byebug


    @resource =  resource_collection.build(resource_params)
    if params.has_key?(:just_validate)
      @resource.valid?
    else
      # byebug
      @resource.save
      begin
        unless @resource.errors.any?
          flash.now[:success] = t "common.messages.#{@resource.class.name.underscore}.create.success",
            resource: (url_for([@parent_scope, @parent_resource, @resource]) rescue url_for([@parent_scope, @resource])), default: "Ресурс успешно создан"
        end
      rescue
      end
    end

    respond_to do |format|
      format.js {}
      format.json { render json: @resource }
    end
  end


  def update
      if params[:restore]
        @resource.restore
        @resource.save!
      else
        @resource.update_attributes(resource_params)
      end
      #byebug
      begin
        unless @resource.errors.any?
          flash.now[:success] = t "common.messages.#{@resource.class.name.underscore}.update.success",
            resource: (url_for([@parent_scope, @parent_resource, @resource]) rescue url_for([@parent_scope, @resource])), default: "Ресурс успешно обновлен"
        end
      rescue
      end

    respond_to do |format|
      format.js {}
    end
  end

  def inplace_popup
  end

  def destroy
    @resource.destroy
    begin
      unless @resource.errors.any?
        flash.now[:success] = t "common.messages.#{@resource.class.name.underscore}.destroy.success",
          resource: (url_for([@parent_scope, @parent_resource, @resource]) rescue url_for([@parent_scope, @resource])), default: "Ресурс успешно удален"
      end
    rescue
    end
    respond_to do |format|
      format.js {}
      format.html {redirect_to url_for(@resource_class)}
    end
  end

  # byebug
  unless self.new.respond_to?(:current_user)
    def current_user
      User.new
    end
    helper_method :current_user
  end

  protected
  def validate_user
    # if current_user.present? && (!current_user.manager? || !current_user.has_role?(:owner) || !current_user.has_role?(:client))
    #   if self.class.parent.name != 'My' && params[:format] != "json"
    #     redirect_to my_rfqs_path, notice: t("shared.messages.page_not_found")
    #   end
    # end
  end

  def on_single_resource
  end

  def directory_attrs
    {}
  end

  def _directory_attrs
    default_title    = I18n.t(:"directory.#{@resource_class.name.underscore}.title", default: @resource_class.name.humanize)
    default_subtitle = I18n.t(:"directory.#{@resource_class.name.underscore}.subtitle", default: params[:action])
    {
      icon: "fa-table",
      title:    I18n.t("common.pages.titles.#{@resource_class.name.underscore.pluralize}.#{params[:action]}.title",    default: default_title),
      subtitle: I18n.t("common.pages.titles.#{@resource_class.name.underscore.pluralize}.#{params[:action]}.subtitle", resource: (@resource.respond_to?(:number) ? @resource.number : @resource.name rescue ''), default: default_subtitle)
    }.merge(directory_attrs).merge(@directory_attrs)
  end

  def load_type
    @resource_class = params[:dir_type].classify.constantize
  end

  def resource_collection
    @resource_class.all
  end

  def load_resource
    #byebug
    if params[:id]
      @resource = if params[:restore]
        resource_collection.unscoped.find(params[:id])
      else
        resource_collection.find(params[:id])
      end
    end
  end

  def resource_params(permit = [])

    permit = [permit] unless permit.is_a?(Array)

    #byebug
    _params_to_permit = @resource_class.directory_keys
    _merged_hash = _params_to_permit.inject(Hash.new) {|res, i| i.is_a?(Hash) ? res.deeper_merge(i) : res }

    permit.each do |filter|
      case filter
      when Symbol,String
        _params_to_permit << filter
      when Hash then
#       byebug
        _merged_hash.deeper_merge!(filter)
      end
    end

    _params_to_permit = _params_to_permit.reject {|i| i.is_a?(Hash)}
    _params_to_permit << _merged_hash

    #byebug

    params.require(@resource_class.name.underscore.gsub('/', '_') ).permit(
      _params_to_permit
    )
  end

  def set_title
    if @resource_class.present?
      @page_title = t("common.pages.titles.#{@resource_class.name.pluralize.underscore}.#{params[:action]}.title", default: "directories")
      @page_subtitle = t("common.pages.titles.#{@resource_class.name.pluralize.underscore}.#{params[:action]}.subtitle", resource: (@resource.respond_to?(:number) ? @resource.number : @resource.name rescue ''), default: '')
      @page_subtitle = nil unless @page_subtitle.present?
    end
  end

  def init_directory
    @directory_attrs = {}
  end

  # def self.directory_for(_class, overrides_hash)
  #   @@_directory_overrides[controller_path] = {} unless @@_directory_overrides[controller_path].is_a?(Hash)
  #   @@_directory_overrides[controller_path][_class] = overrides_hash
  # end


  def self.directory_controls(controls_hash)
    @@_directory_controls[controller_path] = controls_hash
  end

  def add_directory_controls(field, control, params = {})
    @@_directory_controls[controller_path].merge!({field => {control: control, render: true}.merge(params) })
  end

  def remove_directory_controls(*args)
    args.map { |e| @@_directory_controls[controller_path].delete(e) }
  end

  def hide_directory_control(field)
    unless @@_directory_controls[controller_path][field].present?
      @@_directory_controls[controller_path][field] = { control: :text }
    end
    @@_directory_controls[controller_path][field][:render] = false
  end

  def show_directory_control(field)
    if @@_directory_controls[controller_path][field]
      @@_directory_controls[controller_path][field].delete(:render)
    end
  end

  def disable_directory_control(field)
    if @@_directory_controls[controller_path][field]
      @@_directory_controls[controller_path][field].merge!({ disabled: true })
    end
  end

  def enable_directory_control(field)
    if @@_directory_controls[controller_path][field]
      @@_directory_controls[controller_path][field].delete(:disabled)
    end
  end

  def control_for(field)
    @@_directory_controls[controller_path][field] rescue nil
  end

  def directory_buttons(buttons_hash)
    @@_directory_buttons[controller_path] = buttons_hash
  end

  def control_for(field)
    @@_directory_controls[controller_path][field] rescue nil
  end

  def get_directory_buttons
    @@_directory_buttons[controller_path]
  end
end

app/helpers/directories/application_helper.rb
module Directories
  module ApplicationHelper
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
               concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
               concat raw(message)
             end)
    end
    nil
  end

  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info' }[flash_type] || flash_type.to_s
  end

  def sanitized_object_name(f)
     f.object_name.gsub(/\]\[|[^-a-zA-Z0-9:.]/, "_").sub(/_$/, "")
  end

  def field_id_for(f,method, form_id = false)
    str = "#{sanitized_object_name(f)}_#{method.to_s.sub(/\?$/,"")}"
    if form_id && f.options[:html].present?
      f_id = f.options[:html][:id]
      "#{str}_#{f_id}"
    else
      str
    end
  end

  def edit_directory_fields_for(resource)
    #byebug
    if resource.persisted?
      controller.edit_overrides_for(resource.class) || resource.class.edit_directory_fields
    else
      controller.create_overrides_for(resource.class) || resource.class.create_directory_fields
    end
  end

  def directory_columns_for(resource_class, fields=nil, no_templates = false)
    columns = []
    _fields = fields || (controller.display_overrides_for(resource_class) || resource_class.directory_fields)
    #byebug
    _fields.each do |field|
      if no_templates
        columns << field
        next
      end

      if field.is_a?(Hash)
        field[field.keys.first].each do |subfield|
          if fields.nil? && lookup_context.exists?("item_#{field.keys.first}_#{subfield}", controller.controller_path , true)
            columns << {field: "#{field.keys.first}.#{subfield}", template: "#{controller.controller_path}/item_#{field.keys.first}_#{subfield}" }
          elsif lookup_context.exists?("item_#{field.keys.first}_#{subfield}", resource_class.name.tableize , true)
            columns << {field: "#{field.keys.first}.#{subfield}", template: "#{resource_class.name.tableize}/item_#{field.keys.first}_#{subfield}" }
          else
            columns <<  "#{field.keys.first}.#{subfield}"
          end

        end
      else
        if fields.nil? && lookup_context.exists?("item_#{field}", controller.controller_path, true)
          columns << {field: field, template: "#{controller.controller_path}/item_#{field}" }
        elsif lookup_context.exists?("item_#{field}", resource_class.name.tableize , true)
          columns << {field: field, template: "#{resource_class.name.tableize}/item_#{field}" }
        else
          columns << field
        end
      end
    end
    #byebug
    columns
  end

  def directory_tab_builder(tabs = [], &block)
    tabs = [tabs] unless tabs.is_a?(Array)
    tabs.map do |tab_id|
      if tab_id.is_a?(Hash)
        {
         tab_id: tab_id[:id],
         tab_data: {partial: "directories/tab_link", tab_id:  tab_id[:id], title: I18n.t(:"directory.tabs.#{tab_id[:id]}"), active:  tab_id[:active] },
         tab_content: block_given? ? capture(tab_id[:id], true, &block) : ""
        }
      else
        {
         tab_id: tab_id,
         tab_data: {partial: "directories/tab_link", tab_id: tab_id, title:  I18n.t(:"directory.tabs.#{tab_id}")  },
         tab_content: block_given? ? capture(tab_id, &block) : ""
        }
      end
    end
  end

  def find_render_template(name, options= {})
    formats = options.select {|k,v| k == :formats}
    formats = { formats: [:html] } unless options.present?

    if lookup_context.exists?("#{name}_item", controller.controller_path , true, [], formats)
      "#{controller.controller_path}/#{name}_item"
    elsif lookup_context.exists?("#{name}_item", @resource_class.name.tableize , true, [], formats)
      "#{@resource_class.name.tableize}/#{name}_item"
    elsif lookup_context.exists?("#{name}_item", 'directories' , true, [], formats)
      "directories/#{name}_item"
    else
      nil
    end
  end

  def directory_render(name, options = {})
    # partial = find_render_template(name, options)
    # byebug
    # @_partial = {} unless @_partial
    # unless @_partial[name]
    #   if lookup_context.exists?(name, controller.controller_path , true, [], formats)
    #     @_partial[name]  =  "#{controller.controller_path}/#{name}"
    #   elsif lookup_context.exists?(name, @resource_class.name.tableize , true, [], formats)
    #     @_partial[name] =   "#{@resource_class.name.tableize}/#{name}"
    #   else
    #     @_partial[name] =  "directories/#{name}"
    #   end
    # end
    # formats = options.select {|k,v| k== :formats}
    # formats = { formats: [:html] } unless options.present?
    if name.is_a?(Hash)
      options = name
      name = options[:partial].present? ? options[:partial] : options[:template]
    end

    partial = options[:template].nil?
    formats = options.select {|k,v| k== :formats}
    formats = { formats: [:html] } unless options.present?

    directory_template_exist?(name, partial, options)
    if @_partial[name]
      hash = partial ? { :partial =>  @_partial[name] } : { :template =>  @_partial[name] }
      render(hash.reverse_merge(options).merge(formats))
    end
  end


  def directory_template_exist?(name, partial, options = {})
    # byebug
    formats = options.select {|k,v| k== :formats}
    formats = { formats: [:html] } unless options.present?

    #byebug if name == "s_item_sessid"
    @_partial = {} unless @_partial
    unless @_partial.has_key?(name)
      if lookup_context.exists?(name, controller.controller_path , partial, [], formats)
        @_partial[name]  =  "#{controller.controller_path}/#{name}"
        return true
      elsif lookup_context.exists?(name, @resource_class.name.tableize , partial, [], formats)
        @_partial[name] =   "#{@resource_class.name.tableize}/#{name}"
        return true
      elsif lookup_context.exists?(name, "directories", partial, [], formats)
        @_partial[name] =  "directories/#{name}"
        return true
      else
        @_partial[name] = nil
        return false
      end
    else
      return !@_partial[name].nil?
    end

  end


  def content_header(options = {title: "", subtitle: "", icon: ""}, &block)

    options.merge!(:body => capture(&block)) if block_given?
    render(partial: "common/content_header", locals: options)
  end

  def datatable_widget(id,
    options = {
      icon: "",
      title: "",
      source_url: "",
      columns: [],
      order_by: [],
      buttons: [] }, &block)

    options.merge!(id: id, :body => "")
    options.merge!(:body => capture(&block)) if block_given?
    #byebug
    render(partial: "common/datatable_widget", locals: options)
  end

  def freight_pill(caption, value, options = {})
    %(
     	<h4 class="freight-pill">
        <span class="label label-sm label-success #{begin
                                         options[:class]
                                       rescue
                                         ''
                                       end}">
          <span>#{caption} #{value} </span>
        </span>
      </h4>
     ).html_safe
  end

  def scope_t(resource, field)
    scoped = @parent_scope || @parent_resource
    if scoped.present? && !scoped.is_a?(String)
      scoped = scoped.class.name.underscore
    end
    t("directory.#{scoped ? scoped.singularize + '.' : ''}#{resource.class.name.underscore}.fields.#{field}")
  end

  def can_render?(control_hash)
    control_hash[:render].nil? || control_hash[:render]
  end

  def nested_fields_for(resource_class, &block)
    #byebug
    index = 0
    resource_class.directory_nested.each do |nested|
      if nested.is_a?(Hash)
        scope = nested[:scope]
        unless scope.is_a?(Array)
          scope = [scope]
        end
        if (scope.compact.empty? || @parent_scope.nil? || scope.map(&:to_s).include?(@parent_scope))
          yield nested, index if block_given?
          index += 1
        end
      else
        yield nested, index if block_given?
        index += 1
      end
    end
  end

  def select_options(f, field, control_hash)
    # byebug
    if f.object.send(field).present?
      {}
    else
      control_hash[:selected] ? { selected: (control_hash[:selected].is_a?(Symbol) ? send(control_hash[:selected]) : control_hash[:selected]) } : {}
    end
  end
end

app/views/directories/_form.html.erb
<% @_selectivities = [] %>
<fieldset>
	<legend>Введите параметры:</legend>
		<%= f.hidden_field :id %>
    <div class="form-group">
      <div class="col-md-2"></div>
      <div class="col-md-10 text-danger">
        <% f.object.errors[:base].each do |err_msg| %>
          <%= err_msg %>
        <% end %>
      </div>
    </div> 
		<% edit_directory_fields_for(resource).each do |field| %>
			<% next if field==:id %>
			<%= render "directories/supernested", f: f, field: field, resource: resource %>
		<% end %>
</fieldset>




<% if @_selectivities.length > 0 %>
	<%= render "directories/controls/selectivity_scripts", resource: resource %>
<% end %>

app/views/directories/_inplace.html.erb
<%= datatable_widget :"crud-#{@resource_class.name.to_url}",
                     icon: "fa-table",
                     title: t(:"directory.#{@resource_class.name.underscore}.title"),
                     source_url: (url_for([@parent_scope, @resource_class, (params[:filters] || {}).merge(datatables: true, format: :json, scope: @parent_scope)]) rescue directories_url(@resource_class.name.underscore,  (params[:filters] || {}).merge(datatables: true, format: :json)) ),
                     columns: directory_columns_for(@resource_class),
                     buttons: [
                      {
                        text: "Добавить",
                        class: "btn btn-primary",
                        url: (url_for([:new, @parent_scope, @resource_class.name.singularize.to_url, (params[:filters] || {}).merge(format: :js)]) rescue new_directory_url(@resource_class.name.underscore, (params[:filters] || {}).merge(format: :js) ))
                      }
                     ] do %>

    <thead>
      <tr>
        <% @resource_class.directory_fields.each do |field| %>
          <% if field.is_a?(Hash) %>
            <% field[field.keys.first].each do |subfield| %>
              <th><%= t(:"directory.#{@resource_class.name.underscore}.fields.#{field}.#{subfield}") %></th>
            <% end %>
          <% else %>
            <th><%= t(:"directory.#{@resource_class.name.underscore}.fields.#{field}") %></th>
          <% end %>
        <% end %>
      </tr>
    </thead>
    <tbody>
    </tbody>

<% end %>

app/views/directories/_inplace_popup.html.erb
<div class="modal fade" id="<%= params[:popup_id] %>">
    <div class="modal-dialog large">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  data-dismiss="modal" aria-hidden="true">×</button>
                	<h4 class="modal-title"><%= t(:"directory.#{@resource_class.name.underscore}.popup.title") %></h4>

            </div>
            <div class="modal-body">

                <%= datatable_widget :"crud-#{@resource_class.name.to_url}",
                                     icon: "fa-table",
                                     title: t(:"directory.#{@resource_class.name.underscore}.title"),
                                     source_url: (url_for([@parent_scope, @resource_class, (params[:filters] || {}).merge({datatables: true, no_templates: true, format: :json, scope: @parent_scope})]) rescue directories_url(@resource_class.name.underscore,  (params[:filters] || {}).merge(datatables: true, no_templates: true, format: :json)) ),
                                     columns: directory_columns_for(@resource_class, nil, true),
                                     buttons: [
                                      {
                                        text: "Новый",
                                        class: "btn btn-primary",
                                        url: (url_for([:new, @parent_scope, @resource_class.name.singularize.to_url, (params[:filters] || {}).merge(format: :js)]) rescue new_directory_url(@resource_class.name.underscore, (params[:filters] || {}).merge(format: :js) ))
                                      }],
                                     on_select: %Q{
                                     function() {
                                          console.log(this);
                                          _table = $(this).closest('table').dataTable();
                                          _rowData = _table.api().row(this).data();
                                          console.log(_rowData);

                                          $('##{params[:field_id]}_id').val(_rowData.id).trigger('change');
                                          $('##{params[:field_id]}_value').val(_rowData.#{params[:value_field]});
                                          $('##{params[:field_id]}_remove').removeClass('hide');
                                          $('##{params[:popup_id]}').modal('toggle');
                                        }

                                      }  do %>



                    <thead>
                      <tr>
              <% (controller.display_overrides_for(@resource_class) || @resource_class.directory_fields).each do |field| %>
                <% if field.is_a?(Hash) %>
                  <% field[field.keys.first].each do |subfield| %>
                    <th><%= t(:"directory.#{@resource_class.name.underscore}.#{field.keys.first}.#{subfield}") %></th>
                  <% end %>
                <% else %>
                  <th><%= t(:"directory.#{@resource_class.name.underscore}.fields.#{field}") %></th>
                <% end %>
              <% end %>

                      </tr>
                    </thead>
                    <tbody>
                    </tbody>

                <% end %>


            </div>
            <div class="modal-footer">
              <button type='button'  class="btn dismiss-modal" data-dismiss="modal">
                <%= t(:'shared.buttons.cancel') %>
              </button>
            </div>
        </div>
    </div>
</div>
<!--<script type="text/javascript">
  clickByCancel();
</script>
!-->

app/views/directories/_nested_form.html.erb
<%= n.hidden_field :id %>

<% field[field.keys.first].each do |subfield| %>
	<% next if subfield == :id %>
	<div class='form-group <%= "has-error" if n.object.errors[subfield].any? if n.object%>'>
		<%= n.label subfield.to_sym, class: "col-md-2 text-right" %>
		<div class='col-md-10'>
			<%= n.text_field subfield.to_sym, class: "form-control", disabled: n.object.try(:persisted?) %>

			<% if n.object.errors[subfield].any? %>
				<div class="note note-error"><%= n.object.errors[subfield] %></div>
			<% end if n.object %>
		</div>
	</div>
<% end %>

app/views/directories/_new.html.erb
<div id='<%= dom_id(resource) %>' class="modal fade">
<div  class="modal-dialog large">
  <% options = { remote: true, method: :post,  html: { multipart: true, class: "form-horizontal" }} %>
  <% url = begin
        create_url
      rescue
        url_for([ @parent_resource || @parent_scope, @resource] ) rescue directories_url(@resource_class.name.underscore)
      end
    %>
  <% options.merge!(url: url ) %>
  <%= form_for resource, options do |f| %>
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        ×
      </button>
      <h4 class="modal-title"><%= t("directory.#{@parent_resource ? @parent_resource.class.name.underscore + '.' : ''}#{resource.class.name.underscore}.new.title") %></h4>
    </div>
    <div class="modal-body">

        <%= render "#{resource.class.name.underscore.pluralize}/form", resource: resource, f: f rescue render "directories/form", resource: resource, f: f  %>
        <%= render inject_form, resource: resource, f: f  if defined?(inject_form) %>

    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">
        <%= t(:'shared.buttons.cancel') %>
      </button>
      <%= f.submit t(:'shared.buttons.create'), class: "btn btn-primary" %>
    </div>
  </div><!-- /.modal-content -->
  <% end %>
</div>
</div>

app/views/directories/_resource_actions.html.erb
<div class="btn-group pull-right" id='<%= "#{@resource.class.name.singularize.underscore}_actions"  %>'>
	<button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
		Действия <span style='color: white' class="caret"></span>
	</button>
	<ul class="dropdown-menu">
  		<%= custom_content if defined?(custom_content) %>

		<% if can? :edit, @resource %>
		<li>
			<%= link_to t(:"shared.buttons.edit"), ( url_for([:edit, @parent_scope, @resource, format: :js]) rescue directory_url(:edit, @resource.class.name.underscore, @resource)), remote: true %>
		</li>
		<% end %>


		<% if @resource.respond_to?(:printable?) && @resource.printable? && can?(:print, @resource) %>
			<li><%= link_to t("shared.printable"), (url_for([@resource.class.name.demodulize.underscore.to_sym, @parent_scope, @resource, format: :pdf]) rescue '#'), target: '_blank' %></li>
		<% end %>
		<% #byebug %>

		<% if @resource.respond_to?(:aasm) && current_user.can_any?(@resource.available_steps, @resource) %>
		<%#byebug%>
			<li class="divider"></li>

			<%  @resource.available_steps.each do |step| %>
				<% if can? step, @resource %>
					<%# byebug %>
					<li><%= link_to t("#{@resource.class.name.pluralize.underscore}.transitions.#{step}"), (url_for([:state, @parent_scope, @resource, state: step, format: :js]) rescue '#'), method: :put, remote: true %></li>
				<% end %>
			<% end %>
		<% end %>
		<% if can? :destroy, @resource %>
		<li class="divider"></li>
		<li>
	      <%= link_to t(:'shared.buttons.delete'), ( url_for([@parent_scope, @resource]) rescue directory_url(@resource.class.name.underscore, @resource)) , method: :delete, data: {confirm: t(:"directory.#{ @resource.class.name.underscore}.delete.confirmation", default: t('shared.confirmations.delete')) } %>
		</li>
		<% end %>
		<li class="no-action"><a href="#"><%= t('shared.list.no_actions') %></a></li>
	</ul>
</div>

app/views/directories/_show_info.html.erb
	<%# byebug %>
	<% @resource_class.directory_show.each_with_index do |group,index| %>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#<%= @resource_class.name.to_url %>_<%= @resource.id %>_accordion" href="#<%= @resource_class.name.to_url %>_<%= @resource.id %>_accordion_<%= index %>" aria-expanded="<%= index==0 ? "true" : "false" %>" class="<%= "collapsed" if index > 0%>"> <i class="fa fa-lg fa-angle-down pull-right"></i> <i class="fa fa-lg fa-angle-up pull-right"></i>
					<%= t(:"directory.#{@resource.class.name.underscore}.fields.#{group.keys.first}") %> </a></h4>
			</div>

			<div id="<%= @resource_class.name.to_url %>_<%= @resource.id %>_accordion_<%= index %>" class="panel-collapse collapse <%= index==0 ? "in" : "" %>" aria-expanded="<%= index == 0 ? "true" : "false"%>">
				<div class="panel-body no-padding">
					<table class="table table-bordered table-condensed">
						<tbody>
							<% group[group.keys.first].each do |field| %>
									<%= render "directories/show_info_subfields", scope: "directory.#{@resource_class.name.underscore}" ,field: field, resource: @resource, resource_class: @resource.class, title_col_width: (title_col_width rescue "120px") %>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>


		</div>

	<% end %>

app/views/directories/_show_info_subfields.html.erb
<% if field.is_a?(Hash) %>
	<% field[field.keys.first].each do |subfield| %>
		<%= render "directories/show_info_subfields", scope: "#{scope}.#{field.keys.first}" ,field: subfield, resource: resource.send(field.keys.first), resource_class: resource_class.reflect_on_association(field.keys.first).class_name.constantize if resource.send(field.keys.first) %>
	<% end %>
<% else %>
	<tr>
		<th style='width: <%= defined?(title_col_width) ? title_col_width : "120px" %>' class='text-right'><%= t(:"#{scope}.fields.#{field}") %></th>
		<td><%= directory_template_exist?("s_show_item_#{field}", locals: { resource: resource }, formats: [:html]) ? directory_render("s_show_item_#{field}", locals: { resource: resource }, formats: [:html]) : resource.try(field) %></td>
	</tr>
<% end %>

app/views/directories/index.js.erb
$('#content').html('<%= j directory_render template: "index", formats: [:html] %>');